import { test, expect } from '@playwright/test';
import pg from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { sql } from 'drizzle-orm';
import fs from 'fs';
import path from 'path';
import type { DrizzleClient } from '../../src/shared/db/client.js';
import type { MailpitMessagesResponse } from '../mailpit.interface.js';
import { subscriptionRepositories } from '../../src/shared/db/schema/subscription-repositories.js';
import { subscriptions } from '../../src/shared/db/schema/subscriptions.js';

let drizzleClient: DrizzleClient;
let mailpitApiUrl: string;
let pool: pg.Pool;

test.beforeAll(async () => {
  // Wait for the .env.e2e file to be generated by the server-runner
  let envFile = '';
  const envPath = path.join(process.cwd(), '.env.e2e');
  for (let i = 0; i < 60; i++) {
    if (fs.existsSync(envPath)) {
      envFile = fs.readFileSync(envPath, 'utf-8');
      break;
    }
    await new Promise((res) => setTimeout(res, 1000));
  }

  if (!envFile)
    throw new Error('.env.e2e file was not created by the server runner');

  const envs: Record<string, string> = {};
  envFile.split('\n').forEach((line) => {
    const [key, ...vals] = line.split('=');
    if (key && vals.length) {
      envs[key] = vals.join('=');
    }
  });

  mailpitApiUrl = envs.MAILPIT_API_URL!;
  pool = new pg.Pool({ connectionString: envs.DATABASE_URL });
  drizzleClient = drizzle({ client: pool });
});

test.afterAll(async () => {
  if (pool) {
    await pool.end();
  }

  const envFilePath = path.join(process.cwd(), '.env.e2e');
  if (fs.existsSync(envFilePath)) fs.unlinkSync(envFilePath);
});

test.beforeEach(async () => {
  await drizzleClient.execute(
    sql`TRUNCATE TABLE subscriptions, subscription_repositories, subscribe_sagas RESTART IDENTITY CASCADE`,
  );
  await fetch(`${mailpitApiUrl}/api/v1/messages`, { method: 'DELETE' });
});

test('should successfully subscribe, confirm, and list subscriptions', async ({
  page,
}) => {
  // Pre-seed local repo copy so subscribe uses the sync path (201 + email)
  await drizzleClient
    .insert(subscriptionRepositories)
    .values({ id: '00000000-0000-0000-0000-000000000001', name: 'owner/repo' });

  await page.goto('/');

  await page.fill('#apiKey', 'secret-api-key');
  await page.fill('#subEmail', 'test-e2e@example.com');
  await page.fill('#subRepo', 'owner/repo');
  await page.click('button:has-text("Subscribe to Releases")');

  await expect(page.locator('#message')).toHaveText(
    'Successfully subscribed! Please check your email to confirm.',
    { timeout: 15000 },
  );
  await expect(page.locator('#message')).toHaveClass(/success/);

  // Check Mailpit for confirmation email
  let mailData: MailpitMessagesResponse = { total: 0, messages: [] };
  for (let i = 0; i < 30; i++) {
    const mailResponse = await fetch(`${mailpitApiUrl}/api/v1/messages`);
    mailData = (await mailResponse.json()) as MailpitMessagesResponse;
    if (mailData.total > 0) break;
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  expect(mailData.total).toBe(1);
  const emailId = mailData.messages[0]!.ID;

  const emailSourceResponse = await fetch(
    `${mailpitApiUrl}/api/v1/message/${emailId}`,
  );
  const emailSource = (await emailSourceResponse.json()) as { HTML: string };
  const htmlBody = emailSource.HTML;

  const match = htmlBody.match(/href="([^"]+)"/);
  expect(match).toBeTruthy();
  const confirmLink = match![1];
  expect(confirmLink).toBeDefined();

  // Replace port 3000 with test server port 3002
  const localConfirmLink = confirmLink!.replace('3000', '3002');

  const confirmRes = await page.request.get(localConfirmLink);
  expect(confirmRes.ok()).toBeTruthy();
  const confirmJson = await confirmRes.json();
  expect(confirmJson.message).toBe('Subscription confirmed successfully.');

  // View Subscriptions
  await page.goto('/');
  await page.fill('#apiKey', 'secret-api-key');
  await page.fill('#viewEmail', 'test-e2e@example.com');
  await page.click('button:has-text("View Subscriptions")');

  await expect(page.locator('#subscriptionsList')).toContainText('owner/repo');
  await expect(page.locator('#subscriptionsList')).toContainText('✅ Confirmed');
});

test('should show error when already subscribed to a repo', async ({ page }) => {
  // Pre-seed repo + existing subscription
  const [localRepo] = await drizzleClient
    .insert(subscriptionRepositories)
    .values({ id: '00000000-0000-0000-0000-000000000001', name: 'owner/repo' })
    .returning();
  if (!localRepo) throw new Error('Failed to insert test repo');

  await drizzleClient.insert(subscriptions).values({
    email: 'test-e2e@example.com',
    githubRepositoryId: localRepo.id,
    confirmed: true,
  });

  await page.goto('/');
  await page.fill('#apiKey', 'secret-api-key');
  await page.fill('#subEmail', 'test-e2e@example.com');
  await page.fill('#subRepo', 'owner/repo');
  await page.click('button:has-text("Subscribe to Releases")');

  await expect(page.locator('#message')).toHaveClass(/error/, {
    timeout: 15000,
  });
});

test('should show empty list for email with no subscriptions', async ({
  page,
}) => {
  await page.goto('/');
  await page.fill('#apiKey', 'secret-api-key');
  await page.fill('#viewEmail', 'nobody@example.com');
  await page.click('button:has-text("View Subscriptions")');

  await expect(page.locator('#subscriptionsList')).toContainText(
    'No active subscriptions found for this email.',
  );
});
